---
- name: Install Dev Tools |  'Development tools' package group
  dnf:
    name: "@Development tools"

- name: Installing Dependencies 
  dnf: 
    name: "{{ packages }}"
  vars:
    packages:
    - liberation-fonts 
    - sysstat 
    - vim 
    - telnet 
    - unzip 
    - jq 
    - gcc 
    - kernel-devel 
    - kernel-headers 
    - dnf-plugins-core 
    - python3-pip 
    - iproute-tc 
    - rpm-ostree

- name: Disable Select Services
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
  - firewalld
  - systemd-resolved

- name: Disabling SELinux
  selinux:
     state: disabled
  register: selinuxdisabled

- name: Print the changes in Configurtion file 
  command: grep SELINUX /etc/sysconfig/selinux
  register: sevalue

- debug:
        var: sevalue.stdout_lines

- name: Wait for 5 Second and Reboot 
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: selinuxdisabled is changed
